apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: web
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: nginx-demo
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
